In [59]:
import pandas as pd
pf = pd.read_csv('./panel_fin.csv')
#pf = pf[pf['Quarter']>80]
pf[pf['l_ret']=='.']['l_ret'] = 0.0
pf[['l_ret']] = pf[['l_ret']].astype('float')
pf.to_csv('panel_fin.csv')
pf = pf.set_index(['Entity', 'Quarter'])
pf

/usr/local/lib/python3.7/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)

                Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1 accyearquarter  \
Entity Quarter
1.0    1.0               0           0.0             0.0         1987Q2
       2.0               1           1.0             1.0         1987Q3
       3.0               2           2.0             2.0         1987Q4
       4.0               3           3.0             3.0         1988Q1
       5.0               4           4.0             4.0         1988Q2
...                    ...           ...             ...            ...
868.0  90.0          33126       33126.0         33126.0         2009Q3
       91.0          33127       33127.0         33127.0         2009Q4
       92.0          33128       33128.0         33128.0         2010Q1
       93.0          33129       33129.0         33129.0         2010Q2
       94.0          33130       33130.0         33130.0         2010Q3

                     ret     l_ret     l_btm     l_e_p     l_roe
Entity Quarter
1.0    1.0      0.084797  0.173989  0.736854  0.053641  0.077236
       2.0     -0.088159  0.084797  0.714998  0.048519  0.071157
       3.0     -0.028706 -0.088159  0.806114  0.043239  0.054758
       4.0      0.426411 -0.028706  0.867564  0.056453  0.067787
       5.0     -0.003121  0.426411  0.655631  0.051137  0.083884
...                  ...       ...       ...       ...       ...
868.0  90.0    -0.003521 -0.069869  1.823687  0.080381  0.047305
       91.0     0.074205 -0.003521  1.809950  0.083937  0.045864
       92.0     0.116886  0.074205  1.776207  0.080056  0.047537
       93.0    -0.033488  0.116886  1.640578  0.084485  0.053119
       94.0     0.117320 -0.033488  1.737450  0.075722  0.044630

[33131 rows x 9 columns]

In [57]:
from linearmodels.panel import PooledOLS
from linearmodels.panel import PooledOLS
import statsmodels.api as sm
pf = pd.read_csv('./panel_fin.csv')
pf = pf.set_index(['Entity', 'Quarter'])

exog_vars = ['l_ret','l_btm','l_e_p']
exog = sm.add_constant(pf[exog_vars])
mod = PooledOLS(pf.ret, exog)
pooled_res = mod.fit()
print(pooled_res)

                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:                    ret   R-squared:                        0.0348
Estimator:                  PooledOLS   R-squared (Between):              0.0328
No. Observations:               33131   R-squared (Within):               0.0328
Date:                Sat, Nov 28 2020   R-squared (Overall):              0.0348
Time:                        17:50:23   Log-likelihood                 1.335e+04
Cov. Estimator:            Unadjusted
                                        F-statistic:                      397.94
Entities:                         867   P-value                           0.0000
Avg Obs:                       38.213   Distribution:                 F(3,33127)
Min Obs:                       1.0000
Max Obs:                       388.00   F-statistic (robust):             397.94
                                        P-value                           0.0000
Time periods:                      95   Distribution:                 F(3,33127)
Avg Obs:                       348.75
Min Obs:                       205.00
Max Obs:                       466.00

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
const          0.0054     0.0015     3.5055     0.0005      0.0024      0.0084
l_ret         -0.0052     0.0054    -0.9703     0.3319     -0.0157      0.0053
l_btm          0.0196     0.0014     14.222     0.0000      0.0169      0.0223
l_e_p          0.5208     0.0153     34.111     0.0000      0.4909      0.5508
==============================================================================